### ISSUE TITLE
doesn't take ~/.clangd into account

### ISSUE THREAD

**Issue by GopherJ** [clangd/coc-clangd#679]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

1. https://github.com/GopherJ/dotfiles/tree/master/cmake
2. edit cmake/src/kernel.cu

**Logs**
![image](https://github.com/clangd/coc-clangd/assets/33961674/732523fb-01ae-4f4d-9864-808469c9ce1d)

**System information**
Clangd version (from the log, or `clangd --version`): 15.0.7
clangd extension version (from `:CocInfo`): 0.30.2
Operating system: x86_64-pc-linux-gnu

**Comment by GopherJ** [comment]
I encountered  a clangd issue: https://github.com/clangd/clangd/issues/1142, so I tried to create ~/.clangd file with the following content:

```
CompileFlags:
  Add: -Wno-unknown-warning-option
  Remove: [-m*, -f*, -forward-unknown-to-host-compiler, --generate-code*]
Diagnostics:
  Suppress: [drv_unknown_argument,drv_unsupported_opt]
```

but it didn't fix the issue
